<a href="https://colab.research.google.com/github/tsrrbbn040/FTDS_NG/blob/main/h8dsft_Linear_Algebra2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Identitas

* Nama : Muhammad Itsar Rabbani
* Batch : 006

In [30]:
import numpy as np

# 1. Buatlah Tensor di bawah ini dengan Python

ambil contoh penulisan dari kode.id materi W2 D2 AM

```
[
  [[23, 50],
  [7, 12]],
  [[57,67],
  [99,43]],
  [[75, 21],
  [57, 12]],
  [[87, 26],
  [18, 84]
  ]
  ```
maka,

In [12]:
t = np.array(
  [
  [[23, 50],
  [7, 12]],
  [[57,67],
  [99,43]],
  [[75, 21],
  [57, 12]],
  [[87, 26],
  [18, 84]
  ]
  ])

#pembuktian tensor
print(t.shape)

#bentuk visual
print(t)

(4, 2, 2)
[[[23 50]
  [ 7 12]]

 [[57 67]
  [99 43]]

 [[75 21]
  [57 12]]

 [[87 26]
  [18 84]]]


# 2. Lakukan perkalian  terhadap matrix berikut:

```
A = [[23, 50, 19], [7, 12, 109], [57, 67, 98]]

B = [[17, 22, 19]]
```

maka,

In [8]:
#input ke numpy
a = np.array([[23, 50, 19], [7, 12, 109], [57, 67, 98]])
b = np.array([17, 22, 19])

In [15]:
#Cara 1
AB = a@b
print(AB)

[1852 2454 4305]


In [16]:
#Cara 2
A_B = a.dot(b)
print(A_B)

[1852 2454 4305]


# 3. Lakukan Transpose, Hitung Determinan, dan Inverse terhadap matrix di bawah ini:    
```
A = [[23, 50, 19], [7. 12. 109], [57, 67, 98]]
```

In [20]:
#Input array
A = np.array([[23, 50, 19], [7, 12, 109], [57, 67, 98]])
print(A)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]


**Transpose**

In [37]:
#syntax = A.T
#hasil
print("Transpose dari matriks A ="
  , A.T)

Transpose dari matriks A = [[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


**Determinan**

In [35]:
#import function
from numpy.linalg import det

In [36]:
#hasil determinan
print("Determinan matriks A =", det(A))

Determinan matriks A = 131344.0000000002


**Invers**

In [38]:
#import function
from numpy.linalg import inv

In [40]:
#hasil invers matriks A
#Cara 1
inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])

In [42]:
#hasil invers matriks A
#Cara 2
print(np.linalg.inv(A))

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
